In [ ]:
python中list/tuple/dict/set的区别
list:  有序集合，key可以重复，随时增删改[]
tuple: 有序集合，key可以重复，但一旦初始化就无法修改()
dict:  键值对（key-value）方式存储，查找速度快{}
set:   无序集合，key不能重复set()
    
set一般是集合操作，比如并集、交集
dict查找速度比set快，但是消耗内存大，用空间换时间

In [44]:
# list
list = ['abcd', 786, .23, "runoob", True]
tinylist = [123, 'run']
print (list)
print (list[0])
print (list[1:-1])
print (list[-1])
print (list * 2)
print (list + tinylist) # 连接两个list
# 修改list中的元素
list[0] = 23
list[2:4] = [12, 34]
print (list)
print ('----------------')

# tuple
tuple = ['abcd', 786, .23, "runoob", True]
# 和上面list的操作都一样，唯独就是不能进行修改
tuple[0] = 'ab' #!!!报错
print ('----------------')

# dict
dict = {}
dict['one'] = 1
dict[2] = "2"
dict = {'name':'runoob', '1':1, 2:2}
print (dict)
print (dict[2])
print (dict.keys())
print (dict.values())
print ('----------------')

# set
student = {'Tom', 'Jim', 'Mary', 'Tom', 'Jack', 'Rose'}
print(student)   # 输出集合，重复的元素被自动去掉

# 成员测试
if('Rose' in student):
    print('Rose 在集合中')
else :
    print('Rose 不在集合中')

# set可以进行集合运算
a = set('abracadabra')
b = set('alacazam')

print(a)
print(a - b)     # a和b的差集
print(a | b)     # a和b的并集
print(a & b)     # a和b的交集
print(a ^ b)     # a和b中不同时存在的元素

['abcd', 786, 0.23, 'runoob', True]
abcd
[786, 0.23, 'runoob']
True
['abcd', 786, 0.23, 'runoob', True, 'abcd', 786, 0.23, 'runoob', True]
['abcd', 786, 0.23, 'runoob', True, 123, 'run']
[23, 786, 12, 34, True]
----------------
----------------
{'name': 'runoob', '1': 1, 2: 2}
2
dict_keys(['name', '1', 2])
dict_values(['runoob', 1, 2])
----------------
{'Rose', 'Jim', 'Tom', 'Jack', 'Mary'}
Rose 在集合中


TypeError: 'set' object is not callable

In [13]:
# int, float, str, bool四种变量类型
counter = 100
miles = 1000.0
name = "runoob"
flag = True

print (counter)
print (type(counter))
print (miles)
print (type(miles))
print (name)
print (type(name))
print (flag)
print (type(flag))

100
<class 'int'>
1000.0
<class 'float'>
runoob
<class 'str'>
True
<class 'bool'>


In [11]:
# 可以连续赋值
a, b, c = 1, 2., "runoob"

In [ ]:
# 可以使用type或isinstance()判断类型, 区别:
type()不会认为子类是一种父类类型。
isinstance()会认为子类是一种父类类型。

In [14]:
# 可以使用del删除变量引用
var = 3
print (var)
del var
print (var)

3


NameError: name 'var' is not defined

In [20]:
# 对str使用下标截取  \n转义字符
str = 'Runoob'

print (str)
print (str[-1])
print (str[0:-1])
print (str[0:])
print (str[2:5])
print (str * 2)
print (str + "TEST")

Runoob
b
Runoo
Runoob
noo
RunoobRunoob
RunoobTEST


# Runoob Python练习100例
http://www.runoob.com/python/python-100-examples.html

In [10]:
# Python 练习实例2
i = int(input('净利润:'))
arr = [1000000, 600000, 400000, 200000, 100000, 0]
rat = [0.01, 0.015, 0.03, 0.05, 0.075, 0.1]
r = 0

for index in range(0, 6):
    if i > arr[index]:
        r += (i - arr[index])*rat[index]
        i = arr[index]

print (r)

净利润:120000
11500.0


In [11]:
# Python 练习实例5, sort
l = []
for i in range(0, 3):
    l.append(int(input("请输入整数:")))
l.sort()

print (l)

请输入整数:2
请输入整数:9999
请输入整数:0
[0, 2, 9999]


In [12]:
# Python练习实例6, fib
l = []

def fib(n):
    l.append(0)
    l.append(1)
    for i in range(2, n):
        l.append(l[i-2]+l[i-1])
    return l

print (fib(10))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [14]:
# Python 练习实例7, list copy
l = [1, 2, 3, 0, 9]

b = l[:]
print (b)

[1, 2, 3, 0, 9]


In [17]:
# Python 练习实例9, dict的使用
dic = {'a':1, 3:'b', True:"hello"}

for index in dic.keys():
    print (index)
    print (dic[index])

a
1
3
b
True
hello


In [21]:
# Python 练习实例10, time
import time

print (time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time())))
time.sleep(1)
print (time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time())))

2018-06-24 13:21:36
2018-06-24 13:21:37


# Python 函数

# Python 正则表达式

In [10]:
import re
print (re.match('www', 'www.runoob.com').span())
print (re.match('www', 'www.runoob.com').start())
print (re.match('www', 'www.runoob.com').end())
print (re.match('www', 'www.runoob.com').group())
print (re.match('www', 'www.runoob.com').group(0))
print (re.match('www', 'www.runoob.com').groups())

(0, 3)
0
3
www
www
()


In [ ]:
.* 和 .*?的区别
\s匹配任意的空白符（包括空格，制表符(Tab)，换行符，中文全角空格）
\S则是任意不是空白符的字符
?涉及到贪婪模式
当正则表达式中包含能接受重复的限定符时，通常的行为是（在使整个表达式能得到匹配的前提下）匹配尽可能多的字符。以这个表达式为例：a.*b，它将会匹配最长的以a开始，以b结束的字符串。如果用它来搜索aabab的话，它会匹配整个字符串aabab。这被称为贪婪匹配。
有时，我们更需要懒惰匹配，也就是匹配尽可能少的字符。前面给出的限定符都可以被转化为懒惰匹配模式，只要在它后面加上一个问号?。这样.*?就意味着匹配任意数量的重复，但是在能使整个匹配成功的前提下使用最少的重复。现在看看懒惰版的例子吧：
a.*?b匹配最短的，以a开始，以b结束的字符串。如果把它应用于aabab的话，它会匹配aab（第一到第三个字符）和ab（第四到第五个字符）

In [20]:
import re
line = 'Cats are smarter than dogs'

# re.M 多行匹配，影响 ^ 和 $, re.I 使匹配对大小写不敏感
# 点代表的是任意字符。* 代表的是取 0 至 无限长度,问号代表的是非贪婪模式
matchObj = re.match('(.*) are (.*?) (.*)', line, re.M|re.I)
#matchObj = re.match('(.*) are (.*?) .*', line, re.M|re.I)

if matchObj:
    print ('matchObj.group(): ', matchObj.group())
    print ('matchObj.group(0): ', matchObj.group(0))
    print ('matchObj.group(1): ', matchObj.group(1))
    print ('matchObj.group(2): ', matchObj.group(2))
    print ('matchObj.groups: ', matchObj.groups())
else:
    print ('No match!!')

matchObj.group():  Cats are smarter than dogs
matchObj.group(0):  Cats are smarter than dogs
matchObj.group(1):  Cats
matchObj.group(2):  smarter
matchObj.groups:  ('Cats', 'smarter')


In [22]:
import re
line = "Cats are smarter than dogs"

matchObj = re.match('dogs', line, re.M|re.I)
if matchObj:
    print ("match --> matchObj.group(): ", matchObj.group())
else:
    print ("No match!")

matchObj = re.search('dogs', line, re.M|re.I)
if matchObj:
    print ("match --> matchObj.group(): ", matchObj.group())
else:
    print ('No match!')

No match!
match --> matchObj.group():  dogs


In [ ]:
正则表达式^和$有什么用？
[a-z] 可以用来匹配任意位置上的小写字母: "...a..."
^[a-z] 只能匹配以小写字母为行首的行: "a..."
[a-z]$ 只能匹配以小写字母为行尾的行: "...a"
^[a-z]$ 应该只能匹配只有一个小写字母的行: "a"

3、字符$
意义：与^类似,匹配最末的字符.
例如：/t$/不匹配"eater"中的’t’,但匹配"eat"中的’t’.
4、字符*
意义：匹配*前面的字符0次或n次.
例如:/bo*/匹配"A ghost booooed"中的’boooo’或"A bird warbled"中的’b’,但不匹配"Agoat grunted"中的任何字符
参见链接《正则表达式 "^+$"等符号意义》，Link: https://blog.csdn.net/github_36362235/article/details/53302787

In [30]:
import re

phone = '2004-959-559 # 这是一个电话号码'

num = re.sub('#.*$', "hello", phone)
print ('电话号码替换后变为: ', num)

电话号码替换后变为:  2004-959-559 hello


# Python 多线程

In [63]:
# Python Multi-threading
import _thread
import time

# 为线程定义一个函数
def print_time(threadName, delay):
    count = 0
    while count<5:
        time.sleep(delay)
        count+=1
        print ("%s: %s" % (threadName, time.ctime(time.time())))
        
try:
    _thread.start_new_thread(print_time, ("thread-1", 2))
    _thread.start_new_thread(print_time, ("thread-2", 4))
except:
    print ("Error: 无法启动线程")
    
while 1:
    pass

thread-1: Tue Jun 26 22:41:08 2018
thread-2: Tue Jun 26 22:41:10 2018
thread-1: Tue Jun 26 22:41:10 2018
thread-1: Tue Jun 26 22:41:12 2018
thread-2: Tue Jun 26 22:41:14 2018
thread-1: Tue Jun 26 22:41:14 2018
thread-1: Tue Jun 26 22:41:16 2018
thread-2: Tue Jun 26 22:41:18 2018
thread-2: Tue Jun 26 22:41:22 2018
thread-2: Tue Jun 26 22:41:26 2018


KeyboardInterrupt: 

In [72]:
import threading
import time

exitFlag = 0

class myThread (threading.Thread):
    def __init__(self, threadID, name, counter):
        threading.Thread.__init__(self)
        self.threadID = threadID
        self.name = name
        self.counter = counter
        
    def run(self):
        print ('开始线程: '+ self.name)
        print_time(self.name, self.counter, 5)
        print ('退出线程: '+ self.name)

def print_time(threadName, delay, counter):
    while counter:
        if exitFlag:
            threadName.exit()
        time.sleep(delay)
        print ('%s: %s' % (threadName, time.ctime(time.time())))
        counter -= 1
        
thread1 = myThread(1, 'Thread-1', 1)
thread2 = myThread(2, 'Thread-2', 2)

thread1.start()
thread2.start()
thread1.join()
thread2.join()
print ('退出主线程')

开始线程: Thread-1
开始线程: Thread-2
Thread-1: Tue Jun 26 23:14:00 2018
Thread-1: Tue Jun 26 23:14:01 2018Thread-2: Tue Jun 26 23:14:01 2018

Thread-1: Tue Jun 26 23:14:02 2018
Thread-2: Tue Jun 26 23:14:03 2018
Thread-1: Tue Jun 26 23:14:03 2018
Thread-1: Tue Jun 26 23:14:04 2018
退出线程: Thread-1
Thread-2: Tue Jun 26 23:14:05 2018
Thread-2: Tue Jun 26 23:14:07 2018
Thread-2: Tue Jun 26 23:14:09 2018
退出主线程退出线程: Thread-2



In [77]:
import threading
import time

class myThread (threading.Thread):
    def __init__(self, threadID, name, counter):
        threading.Thread.__init__(self)
        self.threadID = threadID
        self.name = name
        self.counter = counter
        
    def run(self):
        print ('开启线程: ' + self.name)
        
        threadLock.acquire()
        print_time(self.name, self.counter, 3)
        threadLock.release()
        
def print_time(threadName, delay, counter):
    while counter:
        time.sleep(delay)
        print ('%s: %s' % (threadName, time.ctime(time.time())))
        counter -= 1
        
# threadLock = threading.Lock()
threadLock = threading.RLock()
threads = []

thread1 = myThread(1, "Thread-1", 1)
thread2 = myThread(2, "Thread-2", 2)

thread1.start()
thread2.start()

threads.append(thread1)
threads.append(thread2)

for t in threads:
    t.join()

print ('退出主线程')

开启线程: Thread-2开启线程: Thread-1

Thread-1: Tue Jun 26 23:18:27 2018
Thread-1: Tue Jun 26 23:18:28 2018
Thread-1: Tue Jun 26 23:18:29 2018
Thread-2: Tue Jun 26 23:18:31 2018
Thread-2: Tue Jun 26 23:18:33 2018
Thread-2: Tue Jun 26 23:18:35 2018退出主线程



# Python 锁 中Lock和RLock的区别，参见
Thread Synchronization Mechanisms in Python - Fredrik Lundh | July 2007, Link: http://effbot.org/zone/thread-synchronization.htm
这里直接摘录

In [ ]:
在threading模块中，定义两种类型的锁：threading.Lock和threading.RLock。它们之间有一点细微的区别，通过比较下面两段代码来说明：

import threading  
lock = threading.Lock() #Lock对象  
lock.acquire()  
lock.acquire()  #产生了死锁。  
lock.release()  
lock.release()  
import threading  
rLock = threading.RLock()  #RLock对象  
rLock.acquire()  
rLock.acquire() #在同一线程内，程序不会堵塞。  
rLock.release()  
rLock.release()  

　　这两种琐的主要区别是：RLock允许在同一线程中被多次acquire。而Lock却不允许这种情况。注意：如果使用RLock，那么acquire和release必须成对出现，即调用了n次acquire，必须调用n次的release才能真正释放所占用的锁。threading.Condition
　　可以把Condiftion理解为一把高级的锁，它提供了比Lock, RLock更高级的功能，允许我们能够控制复杂的线程同步问题。threadiong.Condition在内部维护一个锁对象（默认是RLock），可以在创建Condigtion对象的时候把锁对象作为参数传入。Condition也提供了acquire, release方法，其含义与锁的acquire, release方法一致，其实它只是简单的调用内部锁对象的对应的方法而已。Condition还提供了如下方法(特别要注意：这些方法只有在占用锁(acquire)之后才能调用，否则将会报RuntimeError异常。)：

Condition.wait([timeout]):  
　　wait方法释放内部所占用的锁，同时线程被挂起，直至接收到通知被唤醒或超时（如果提供了timeout参数的话）。当线程被唤醒并重新占有锁的时候，程序才会继续执行下去。

Condition.notify():
　　唤醒一个挂起的线程（如果存在挂起的线程）。注意：notify()方法不会释放所占用的锁。

Condition.notify_all()
Condition.notifyAll()
　　唤醒所有挂起的线程（如果存在挂起的线程）。注意：这些方法不会释放所占用的锁。

In [ ]:
资源总是有限的，程序运行如果对同一个对象进行操作，则有可能造成资源的争用，甚至导致死锁 
也可能导致读写混乱

锁提供如下方法： 
1.Lock.acquire([blocking]) 
2.Lock.release() 
3.threading.Lock() 加载线程的锁对象，是一个基本的锁对象，一次只能一个锁定，其余锁请求，需等待锁释放后才能获取
4.threading.RLock() 多重锁，在同一线程中可用被多次acquire。如果使用RLock，那么acquire和release必须成对出现， 
调用了n次acquire锁请求，则必须调用n次的release才能在线程中释放锁对象

In [ ]:
The below article originally comes from http://effbot.org/zone/thread-synchronization.htm

Thread Synchronization Mechanisms in Python
Fredrik Lundh | July 2007

This article discusses how to synchronize access to shared resources, and otherwise coordinate execution of threads.

Synchronizing Access to Shared Resources #
One important issue when using threads is to avoid conflicts when more than one thread needs to access a single variable or other resource. If you’re not careful, overlapping accesses or modifications from multiple threads may cause all kinds of problems, and what’s worse, those problems have a tendency of appearing only under heavy load, or on your production servers, or on some faster hardware that’s only used by one of your customers.

For example, consider a program that does some kind of processing, and keeps track of how many items it has processed:

counter = 0

def process_item(item):
    global counter
    ... do something with item ...
    counter += 1
If you call this function from more than one thread, you’ll find that the counter isn’t necessarily accurate. It works in most cases, but sometimes misses one or more items. The reason for this is that the increment operation is actually executed in three steps; first, the interpreter fetches the current value of the counter, then it calculates the new value, and finally, it writes the new value back to the variable.

If another thread gets control after the current thread has fetched the variable, it may fetch the variable, increment it, and write it back, before the current thread does the same thing. And since they’re both seeing the same original value, only one item will be accounted for.

Another common problem is access to incomplete or inconsistent state, which can happen if one thread is initializing or updating some non-trivial data structure, and another thread attempts to read the structure while it’s being updated.

Atomic Operations #
The simplest way to synchronize access to shared variables or other resources is to rely on atomic operations in the interpreter. An atomic operation is an operation that is carried out in a single execution step, without any chance that another thread gets control.

In general, this approach only works if the shared resource consists of a single instance of a core data type, such as a string variable, a number, or a list or dictionary. Here are some thread-safe operations:

reading or replacing a single instance attribute
reading or replacing a single global variable
fetching an item from a list
modifying a list in place (e.g. adding an item using append)
fetching an item from a dictionary
modifying a dictionary in place (e.g. adding an item, or calling the clear method)
Note that as mentioned earlier, operations that read a variable or attribute, modifies it, and then writes it back are not thread-safe. Another thread may update the variable after it’s been read by the current thread, but before it’s been updated.

Also note that Python code may be executed when objects are destroyed, so even seemingly simple operations may cause other threads to run, and may thus cause conflicts. When in doubt, use explicit locks.

Locks #
Locks are the most fundamental synchronization mechanism provided by the threading module. At any time, a lock can be held by a single thread, or by no thread at all. If a thread attempts to hold a lock that’s already held by some other thread, execution of the first thread is halted until the lock is released.

Locks are typically used to synchronize access to a shared resource. For each shared resource, create a Lock object. When you need to access the resource, call acquire to hold the lock (this will wait for the lock to be released, if necessary), and call release to release it:

lock = Lock()

lock.acquire() # will block if lock is already held
... access shared resource
lock.release()
For proper operation, it’s important to release the lock even if something goes wrong when accessing the resource. You can use try-finally for this purpose:

lock.acquire()
try:
    ... access shared resource
finally:
    lock.release() # release lock, no matter what
In Python 2.5 and later, you can also use the with statement. When used with a lock, this statement automatically acquires the lock before entering the block, and releases it when leaving the block:

from __future__ import with_statement # 2.5 only

with lock:
    ... access shared resource
The acquire method takes an optional wait flag, which can be used to avoid blocking if the lock is held by someone else. If you pass in False, the method never blocks, but returns False if the lock was already held:

if not lock.acquire(False):
    ... failed to lock the resource
else:
    try:
        ... access shared resource
    finally:
        lock.release()
You can use the locked method to check if the lock is held. Note that you cannot use this method to determine if a call to acquire would block or not; some other thread may have acquired the lock between the method call and the next statement.

if not lock.locked():
    # some other thread may run before we get
    # to the next line
    lock.acquire() # may block anyway
Problems with Simple Locking #
The standard lock object doesn’t care which thread is currently holding the lock; if the lock is held, any thread that attempts to acquire the lock will block, even if the same thread is already holding the lock. Consider the following example:

lock = threading.Lock()

def get_first_part():
    lock.acquire()
    try:
        ... fetch data for first part from shared object
    finally:
        lock.release()
    return data

def get_second_part():
    lock.acquire()
    try:
        ... fetch data for second part from shared object
    finally:
        lock.release()
    return data
Here, we have a shared resource, and two access functions that fetch different parts from the resource. The access functions both use locking to make sure that no other thread can modify the resource while we’re accessing it.

Now, if we want to add a third function that fetches both parts, we quickly get into trouble. The naive approach is to simply call the two functions, and return the combined result:

def get_both_parts():
    first = get_first_part()
    second = get_second_part()
    return first, second
The problem here is that if some other thread modifies the resource between the two calls, we may end up with inconsistent data. The obvious solution to this is to grab the lock in this function as well:

def get_both_parts():
    lock.acquire()
    try:
        first = get_first_part()
        second = get_second_part()
    finally:
        lock.release()
    return first, second
However, this won’t work; the individual access functions will get stuck, because the outer function already holds the lock. To work around this, you can add flags to the access functions that enables the outer function to disable locking, but this is error-prone, and can quickly get out of hand. Fortunately, the threading module contains a more practical lock implementation; re-entrant locks.

Re-Entrant Locks (RLock) #
The RLock class is a version of simple locking that only blocks if the lock is held by another thread. While simple locks will block if the same thread attempts to acquire the same lock twice, a re-entrant lock only blocks if another thread currently holds the lock. If the current thread is trying to acquire a lock that it’s already holding, execution continues as usual.

lock = threading.Lock()
lock.acquire()
lock.acquire() # this will block

lock = threading.RLock()
lock.acquire()
lock.acquire() # this won't block
The main use for this is nested access to shared resources, as illustrated by the example in the previous section. To fix the access methods in that example, just replace the simple lock with a re-entrant lock, and the nested calls will work just fine.

lock = threading.RLock()

def get_first_part():
    ... see above

def get_second_part():
    ... see above

def get_both_parts():
    ... see above
With this in place, you can fetch either the individual parts, or both parts at once, without getting stuck or getting inconsistent data.

Note that this lock keeps track of the recursion level, so you still need to call release once for each call to acquire.

Semaphores #
A semaphore is a more advanced lock mechanism. A semaphore has an internal counter rather than a lock flag, and it only blocks if more than a given number of threads have attempted to hold the semaphore. Depending on how the semaphore is initialized, this allows multiple threads to access the same code section simultaneously.

semaphore = threading.BoundedSemaphore()
semaphore.acquire() # decrements the counter
... access the shared resource
semaphore.release() # increments the counter
The counter is decremented when the semaphore is acquired, and incremented when the semaphore is released. If the counter reaches zero when acquired, the acquiring thread will block. When the semaphore is incremented again, one of the blocking threads (if any) will run.

Semaphores are typically used to limit access to resource with limited capacity, such as a network connection or a database server. Just initialize the counter to the maximum number, and the semaphore implementation will take care of the rest.

max_connections = 10

semaphore = threading.BoundedSemaphore(max_connections)
If you don’t pass in a value, the counter is initialized to 1.

Python’s threading module provides two semaphore implementations; the Semaphore class provides an unlimited semaphore which allows you to call release any number of times to increment the counter. To avoid simple programming errors, it’s usually better to use the BoundedSemaphore class, which considers it to be an error to call release more often than you’ve called acquire.

Synchronization Between Threads #
Locks can also be used for synchronization between threads. The threading module contains several classes designed for this purpose.

Events #
An event is a simple synchronization object; the event represents an internal flag, and threads can wait for the flag to be set, or set or clear the flag themselves.

event = threading.Event()

# a client thread can wait for the flag to be set
event.wait()

# a server thread can set or reset it
event.set()
event.clear()
If the flag is set, the wait method doesn’t do anything. If the flag is cleared, wait will block until it becomes set again. Any number of threads may wait for the same event.

Conditions #
A condition is a more advanced version of the event object. A condition represents some kind of state change in the application, and a thread can wait for a given condition, or signal that the condition has happened. Here’s a simple consumer/producer example. First, you need a condition object:

# represents the addition of an item to a resource
condition = threading.Condition()
The producing thread needs to acquire the condition before it can notify the consumers that a new item is available:

# producer thread
... generate item
condition.acquire()
... add item to resource
condition.notify() # signal that a new item is available
condition.release()
The consumers must acquire the condition (and thus the related lock), and can then attempt to fetch items from the resource:

# consumer thread
condition.acquire()
while True:
    ... get item from resource
    if item:
        break
    condition.wait() # sleep until item becomes available
condition.release()
... process item
The wait method releases the lock, blocks the current thread until another thread calls notify or notifyAll on the same condition, and then reacquires the lock. If multiple threads are waiting, the notify method only wakes up one of the threads, while notifyAll always wakes them all up.

To avoid blocking in wait, you can pass in a timeout value, as a floating-point value in seconds. If given, the method will return after the given time, even if notify hasn’t been called. If you use a timeout, you must inspect the resource to see if something actually happened.

Note that the condition object is associated with a lock, and that lock must be held before you can access the condition. Likewise, the condition lock must be released when you’re done accessing the condition. In production code, you should use try-finally or with, as shown earlier.

To associate the condition with an existing lock, pass the lock to the Condition constructor. This is also useful if you want to use several conditions for a single resource:

lock = threading.RLock()
condition_1 = threading.Condition(lock)
condition_2 = threading.Condition(lock)

# Python 面向对象

In [28]:
# Python 面向对象编程
class testClass:
    i = 12345
    def __init__(self, arg1, arg2):
        self.i = arg1
        self.j = arg2
    def fun1(self):
        return 'hello, world'
    def fun2(self):
        print ('hello')
    
inst = testClass(54321, "this is for j")
print (inst.i)
print (inst.j)
print (inst.fun1())
print (inst)
print (inst.__class__)
print (inst.fun2())

54321
this is for j
hello, world
<class '__main__.testClass'>
hello
None


In [33]:
class people:
    name = ''
    age = 0
    __weight = 0
    def __init__(self, n, a, w):
        self.name = n
        self.age = a
        self.__weight = w
    def speak(self):
        print ('我叫%s, 我%d岁' % (self.name, self.age))

p = people('Alex', 31, 175)
p.speak()
print (p.name)
print (p.age)
print (p.__weight)

我叫Alex, 我31岁
Alex
31


AttributeError: 'people' object has no attribute '__weight'

In [47]:
class people:
    name = ''
    age = 0
    sex = 'M'
    __weight = 0
    def __init__(self, n, a, w):
        self.name = n
        self.age = a
        self.__weight = w
    def speak(self):
        print ('我叫%s, 我今年%d岁' % (self.name, self.age))

class student (people):
    grade = 0
    sex = 'F'
    def __init__(self, n, a, w, g):
        people.__init__(self, n, a, w)
        self.grade = g
    def speak(self):
        print ('我是学生，我叫%s，我今年%d岁，我在读%d年级' % (self.name, self.age, self.grade))

s = student('Alex', 31, 175, 3)
s.speak()
print (s.sex)

我是学生，我叫Alex，我今年31岁，我在读3年级
F


In [53]:
class people:
    name = ''
    age = 0
    __weight = 0
    def __init__(self, n, a, w):
        self.name = n
        self.age = a
        self.__weight = w
    def speak(self):
        print ('我叫%s, 我今年%d岁' % (self.name, self.age))

class student (people):
    grade = ''
    def __init__(self, n, a, w, g):
        people.__init__(self, n, a, w)
        self.grade = g
    def speak(self):
        print ('我是学生，我叫%s，我今年%d岁，我在读%d年级' % (self.name, self.age, self.grade))

s = student('Alex', 31, 175, 4)
s.speak()

class speaker():
    topic = ''
    name = ''
    def __init__(self, n, t):
        self.name = n
        self.topic = t
    def speak(self):
        print ('我是演说家, 我叫%s, 我演讲的主题是%s' % (self.name, self.topic))

#class student_speaker (student, speaker):
class student_speaker (speaker, student):
    a = ''
    def __init__(self, n, a, w, g, t):
        student.__init__(self, n, a, w, g)
        speaker.__init__(self, n, t)
    
ss = student_speaker('Amy', 29, 108, 5, '《为什么我们会成功》')
ss.speak()

我是学生，我叫Alex，我今年31岁，我在读4年级
我是演说家, 我叫Amy, 我演讲的主题是《为什么我们会成功》


In [54]:
class parent:
    def myMethod(self):
        print ('调用父类方法')

class child (parent):
    def myMethod(self):
        print ('调用子类方法')
        
c = child()
c.myMethod()
super(child, c).myMethod()

调用子类方法
调用父类方法


In [55]:
class JustCounter:
    __secretCounter = 0
    publicCounter = 0
    
    def count(self):
        self.__secretCounter += 1
        self.publicCounter += 1
        print (self.__secretCounter)

counter = JustCounter()
counter.count()
counter.count()

print (counter.publicCounter)
print (counter.__secretCounter)

1
2
2


AttributeError: 'JustCounter' object has no attribute '__secretCounter'

In [57]:
class Site:
    def __init__(self, name, url):
        self.name = name
        self.__url = url
    
    def who(self):
        print ('name: ', self.name)
        print ('url: ', self.__url)
        
    def __foo(self):
        print ('这是私有方法foo')
        
    def foo(self):
        print ('这是公共方法foo')
        self.__foo()
        
x = Site('菜鸟教程', 'www.runoob.com')
x.who()
x.foo()
x.__foo()

name:  菜鸟教程
url:  www.runoob.com
这是公共方法foo
这是私有方法foo


AttributeError: 'Site' object has no attribute '__foo'

In [61]:
class people:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def __str__(self):
        return '这个人的名字叫%s, 已经有%d岁了！' % (self.name, self.age)
    
a = people('Alex', 31)
print (a)

这个人的名字叫Alex, 已经有31岁了！


In [62]:
# function and operator overload
class Vector:
    def __init__(self, a, b):
        self.a = a
        self.b = b
    
    def __str__(self):
        return 'Vector(%d, %d)' % (self.a, self.b)
    
    def __add__(self, other):
        return Vector(self.a + other.a, self.b + other.b)
    
v1 = Vector(2, 10)
v2 = Vector(5, -2)
print (v1+v2)

Vector(7, 8)


# Python常用函数总结试验 (以下笔记主要来自CS686-02 ML课程以及相关ppt的cheatsheet)

In [2]:
import numpy as np
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt 
%matplotlib inline
import statsmodels.api as sm 
import patsy

C:\Users\Alex_Guo\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [43]:
# Python list中append和extend的区别
music_media = ['compact disc', '8-track tape', 'long playing record']
new_media = ['DVD Audio disc', 'Super Audio CD']
music_media.append(new_media)
print (music_media)

['compact disc', '8-track tape', 'long playing record', ['DVD Audio disc', 'Super Audio CD']]


In [45]:
# Python list中append和extend的区别
music_media = ['compact disc', '8-track tape', 'long playing record']
new_media = ['DVD Audio disc', 'Super Audio CD']
music_media.extend(new_media)
print (music_media)

['compact disc', '8-track tape', 'long playing record', 'DVD Audio disc', 'Super Audio CD']


In [35]:
# list操作
# list跟tuple最大的区别是list可以重复，tuple不可以
x = []
len(x)
x.append('y')

# position 1, add y
x.insert(1, 'y')

del(x[0])
del(x[0:2])
x.remove('y')
x.pop(1)
# remove很一般，直接删除某个元素
# pop按照索引index position删除元素，返回被你删除的那个元素
# del按照索引index position删除元素，但啥也不返回

x.reverse()
x.sort()
# add two lists
x1+x2
# 3个y构建成一个list名为x
x = ['y']*3
min(x)
max(x)
# return the position of item
x.index['y']
# return the count of item
x.count['y']
# whether a item is in a list
'y' in x

['y', 'y', 'y']

In [37]:
# tuple操作
# list跟tuple最大的区别是list可以重复，tuple不可以，并且tuple一旦初始化就无法修改
# set也是不能重复，但是set可以修改
x = set()
x.append('a')

AttributeError: 'set' object has no attribute 'append'

In [ ]:
# dic操作
x = {}
x['blue'] = 'blue'
x['yellow'] = 'yellow'

x = {'blue': 'blue', 'red': 'red'}
len(x)
x.keys()
x.values()
x.items()
# returns the value of the key or default
x.get('y', None)
# returns the value of the key, if the key is not in the dic, write default into the dic then returns the default
x.setDefault('y', None)
del(x[key])
'y' in x
y = x.copy()
x.update(z)

In [ ]:
# str操作
my_string[3]
my_string[4:9]
my_string.upper()
my_string.lower()
my_string.count('w')
my_string.replace('e', 's')
# 移除字符串头尾的空格
my_string.strip()

In [32]:
# Python查看类型
myList = list(range(1, 9))
type(myList)



list

In [27]:
# 正态分布
myRndNormal = np.random.normal(size=10)

# 均匀分布
# 两个数组ndarray通过concat拼接成pandas的一个data frame
# iloc[][]的使用
x = np.random.uniform(9, 27, 10)
x.dtype
y = 0.5*x + np.random.uniform(-2, 2, 10)
myData = pd.DataFrame(pd.concat([pd.Series(x), pd.Series(y)], axis = 1))
myData.rename(columns={0: "x", 1: "y"}, inplace = True)
myData.head(10)
myData.shape
np.mean(x)
myData.iloc[0][0]
myData.iloc[0]['x']
len(myData)

# 随机选取一个随机数，往list里添加元素
import random

val_sample1 = []
for i in range(1, 100001):
    val_sample1.append(random.choice(myRndUnif))
    
# 产生-5.0到5.0之间的101个均匀间隔的数
for i in np.linspace(-5.0, 5.0, 101):
    XXX
# 产生-5到5.01之间以0.01为间隔的数
for lambda_ in np.arange(-5, 5.01, 0.01):
    XXX
# 使用range
for i in range(0, 9, 1):
    XXX

10

In [30]:
# Numpy对一列数x求mean 求sum
x = np.random.uniform(9, 27, 10)
x.mean()
x.sum()

# 求平方和
a = pgaDataSet.DrvAcc
y_hat = -0.9516*a+174.0788
y_actual = pgaDataSet.AvgDrive

np.sum((y_actual-y_hat)**2)

# 求标准差和平方根
t_star = (copierMnDataSet.y.mean() - 0) / (copierMnDataSet.y.std() / np.sqrt(45))

163.97300783585197

In [ ]:
# iloc的用法
sum_dividend = 0;
sum_divider = 0;
for i in range(0, len(myData)):
    sum_dividend += (myData.iloc[i]['x'] - np.mean(x)) * (myData.iloc[i]['y'] - np.mean(y));
    sum_divider += (myData.iloc[i]['x'] - np.mean(x)) * (myData.iloc[i]['x'] - np.mean(x));
print (sum_dividend/sum_divider)

In [29]:
# Pandas中loc和iloc的区别，前者根据label，后者根据position
mySeries = pd.Series(np.arange(1, 4), index = np.arange(10, 13))
print (mySeries)
print (mySeries.loc[11])
# 如下报错，没有第11个数
# mySeries.iloc[11]
print (mySeries.iloc[2])
print (len(mySeries))

10    1
11    2
12    3
dtype: int32
2
3
3


In [ ]:
# Pandas从csv导入数据
copierMnDataSet = pd.read_csv('copierMaintenanceData.csv', header=None)
copier = pd.read_csv('copierMaintenanceData.csv', names=['y', 'x'])
copierMnDataSet.columns = ['y', 'x']
copierMnDataSet.head(10)

# Pandas从txt导入数据
platsicHardnessDataSet = pd.read_table('plasticHardness.txt', header=None, delim_whitespace=True)
platsicHardnessDataSet.columns = ['BrinellUnits', 'Hrs']
platsicHardnessDataSet.head(2)

In [ ]:
# Pandas拷贝Dataframe并对其修改
modified_SENIC_data_02 = modified_SENIC_data_01.copy(True)
modified_SENIC_data_02.lengthOfStay = modified_SENIC_data_02.lengthOfStay * 192
modified_SENIC_data_02.infectionRisk = modified_SENIC_data_02.infectionRisk * 192

In [ ]:
# Pandas data frame 按行值过滤filter
fourDataSets = pd.read_csv('fourDataSets.csv')
fourDataSets.head(10)

fourDataSets1 = fourDataSets[fourDataSets.dataSet == 1]
fourDataSets2 = fourDataSets[fourDataSets.dataSet == 2]

df[df.sse == df.sse.min()]

# Pandas 画x y散点图
fourDataSets1_lmplot = sns.lmplot("x", "y", data=fourDataSets1, ci=None)
# 或者
temp = fourdata.loc[fourdata['dataSet'] == i, ]
plt.scatter(temp['x'], temp['y'])
plt.show()

# 通过一个list构建柱状图
plt.hist(val_sample1)
plt.title("sample1 values Histogram")
plt.xlabel("Value")
plt.ylabel("Frequency")

In [ ]:
# 打印 print, %d, %s, 四舍五入round
print ("b0 = %s and b1 = %s" % (round(b0, 4), round(b1, 4)))

In [31]:
# NumPy构建数组  由NumPy数组构建Pandas的data frame
output = np.array([[0.285, 0.7443, 0.3742, 'original data'],
[0.285, 142.9063, 0.3742, 'multiply X and Y by 192'],
[0.285, 34.9823, 17.5882, 'multiply Y by 47'],
[0.285, 0.7443, 0.031, 'multiply X by 12']])

output_df = pd.DataFrame(output, columns=['R2', 'b0', 'b1', 'data transformation'])
output_df

R2        b0       b1      data transformation
0  0.285    0.7443   0.3742            original data
1  0.285  142.9063   0.3742  multiply X and Y by 192
2  0.285   34.9823  17.5882         multiply Y by 47
3  0.285    0.7443    0.031         multiply X by 12

In [ ]:
# 类型转换，转为str
print 'regression function: y = ' + str(round(results.params['const'], 3))

# NumPy相关总结试验

In [85]:
# NumPy (Numerical Python)里只包含n-dimensional array一种数据类型，即ndarray，并且所有item的类型要求必须一致
# .shape 求维度，.dtype 求item类型
x = np.array([[1.5, .2, 3], [-99, -98, -97]])
print (x)
print (x.shape)
print (x.dtype)

# NumPy使用自己的np.arange()函数来产生range，不像普通Python那样用range()函数
y = np.arange(5)
# 增长step = 5，10<=x<25
z = np.arange(10, 25, 5)
# 产生0到2之间的9个数，间隔一致
g = np.linspace(0, 2, 9)
m = np.full((2, 2, 2), 7)
print (y.dtype)
print (y)
print (y.shape)
print (z)
print (g)
print (m)
y[1:3] = [99, 98]
print (y)
print (y.shape)

# NumPy为了应对大数据的场景，被设计地会尽可能地节省内存，也就是说，对NumPy的一个ndarray的slicing做操作、会直接影响到原始ndarray
# ，如果你不想影响到原始的ndarray，请使用.copy复制出一个新的slicing
y = np.arange(5)
print (y)
test_slicing = y[1:3]
test_slicing[:] = 789
print (test_slicing)
print (y)

# NumPy的逻辑运算> >= < <= == != | &, True, False, True-1, False-0
print (3 != 2)
# 1可以当True使
if (1):
    print ('nihao')
x = np.arange(5)
print (x > 2)
y = (x>2) | (x<1)
print (y)
# 类型转换, .astype()
print (y.astype(int))
print (x.sum())
print (x.mean())

# 生成随机数，生成正态分布
np.random.seed(1)
z = np.random.normal(1, 6, 5)
print (z)
print (x>z)

[[  1.5   0.2   3. ]
 [-99.  -98.  -97. ]]
(2, 3)
float64
int32
[0 1 2 3 4]
(5,)
[10 15 20]
[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]
[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]
[ 0 99 98  3  4]
(5,)
[0 1 2 3 4]
[789 789]
[  0 789 789   3   4]
True
nihao
[False False False  True  True]
[ True False False  True  True]
[1 0 0 1 1]
10
2.0
[ 10.74607218  -2.67053848  -2.16903051  -5.43781173   6.19244578]
[False  True  True  True False]


In [47]:
# 将ndarray转换为普通的list
y = x.tolist()
y

[[1, 2, 3], [-99, -98, -97]]

In [57]:
# list operation
print (y+y)
# ndarray operation
print (x+x)

z = 1/x
print (z)
print (z.dtype)

[[1, 2, 3], [-99, -98, -97], [1, 2, 3], [-99, -98, -97]]
[[   2    4    6]
 [-198 -196 -194]]
[[ 1.          0.5         0.33333333]
 [-0.01010101 -0.01020408 -0.01030928]]
float64


In [81]:
# np.zeros()
test = np.zeros((3, 4))
test

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [82]:
# np.ones()
test = np.ones((2, 3, 4))
test

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [55]:
# np.empty()
test = np.empty(4)
test

array([  6.98659762e-313,   6.98657828e-313,   6.98659674e-313,
         6.98659676e-313])

# Pandas相关总结试验

In [94]:
# Pandas有两种数据类型，series和data frame，series总是一维的
# 创建series，每个series都自带index信息，index信息默认为整数从0开始，你也可以使用index参数来指定为字母或字串等其它类型
# 注意，index是可以non-unique的，即可以重复
mySeries = pd.Series([99, 98])
print (mySeries)
mySeries = pd.Series(np.arange(1, 5))
print (mySeries)
print (mySeries[1:3])

# return an array
print (mySeries.values)
print (mySeries.index)
print (mySeries.values.dtype)
print (mySeries.index.dtype)

0    99
1    98
dtype: int64
0    1
1    2
2    3
3    4
dtype: int32
1    2
2    3
dtype: int32
[1 2 3 4]
RangeIndex(start=0, stop=4, step=1)
int32
int64


In [107]:
# Series的index也可以不是integer，而是character之类
mySeries = pd.Series(np.arange(1, 5), dtype = 'float', index = ['a', 'b', 'c', 'd'])
print (mySeries)
print (mySeries.index.dtype)

# 所以我们可以借助zip通过dic来构建Series的index, value对儿
mySeries = pd.Series(dict(zip(['a', 'b', 'c', 'd'], np.arange(1, 5))), dtype = 'float')
print (mySeries)

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64
object
a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64


In [110]:
# Pandas中loc v.s. iloc
mySeries = pd.Series(np.arange(1, 4), index = np.arange(10, 13))
print (mySeries)
print (mySeries.loc[11])
# 如下会报错，只能写print (mySeries.iloc[1])
# print (mySeries.iloc[11])

10    1
11    2
12    3
dtype: int32
2


In [111]:
# 两个Series可以直接相加，会依据index自动关联join
mySeries_01 = pd.Series([10, 9, 8, 7], index = ['pi', 'rho', 'theta', 'gamma'])
mySeries_02 = pd.Series([910, 19, 44, 2], index = ['nu', 'chi', 'pi', 'theta'])
print (mySeries_01 + mySeries_02)

chi       NaN
gamma     NaN
nu        NaN
pi       54.0
rho       NaN
theta    10.0
dtype: float64


In [113]:
# Series的index是可以重复的，Non-unique的，操作时会比较特殊
mySeries_01 = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'a', 'c'])
mySeries_02 = pd.Series([99, 98, 97, 96], index = ['a', 'a', 'd', 'c'])
print (mySeries_01['a'])
print (mySeries_01 + mySeries_02)

a    1
a    3
dtype: int64
a    100.0
a     99.0
a    102.0
a    101.0
b      NaN
c    100.0
d      NaN
dtype: float64
